### PR TITLE
Iterations

### PR DESCRIPTION
**Pull request by stp-ip**
**What this PR does / why we need it**:
* Better header readability
* Upgrade to latest Syna master
* Reordered navigation and projects
* Updated documentation

### CODE REVIEW

**Comment by stp-ip** [comment]
@mpourismaiel @erbesharat

**Review by mpourismaiel — CHANGES_REQUESTED** [review]
Since the change to content fragment the subnav has a bit too much padding. It can be removed with `p-0` or `py-0` as padding value for the fragment. Everything else looks great.

Love the new duo tone hero background btw.

**Comment by stp-ip** [comment]
#13 added a separate issue on this.

**Review by mpourismaiel — APPROVED** [review]
Sounds good. :+1:

**Pull request merged**
